// import './jsx/jsx-basic-1';
// import './jsx/jsx-basic-2';
// import './jsx/jsx-with-style';
// import './test/test';
// import './component-basic/first-component';
// import './component-basic/animal-container';
// import './component-basic/props-basic-1';
// import './component-basic/props-children';
// import './component-basic/defalut-props';
// import './component-intermediate/state-study-1';
// import './component-intermediate/state-study-2';
// import './component-intermediate/state-study-3';
// import './test/Quiz';
// import './component-intermediate/state-study-with-inner-object';
// import './component-intermediate/counter-with-hook-caveat';
// import './js-study/immutable-list-manipulation';
import './component-intermediate/manipulate-list';